/*
 * Copyright (c) 2015-2020, Onbings. All rights reserved.
 *
 * THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY OF ANY
 * KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A PARTICULAR
 * PURPOSE.
 *
 * This module defines the bof module interface
 *
 * Name:        bofosd.h
 * Author:      Bernard HARMEL: onbings@gmail.com
 * Web:			    onbings.dscloud.me
 * Revision:    1.0
 *
 * Rem:         Nothing
 *
 * History:
 *
 * V 1.00  Dec 26 2013  BHA : Initial release
 */
#pragma once
/*
cmake -DCMAKE_TOOLCHAIN_FILE=C:/pro/vcpkg/scripts/buildsystems/vcpkg.cmake -DBUILD_SHARED_LIBS=OFF -DVCPKG_TARGET_TRIPLET=evs-x64-swx-windows-static -DBOFSTD_GENERATE_HELP=ONN C:/pro/github/bofstd
*/
#include "boferr.h"
#include <cstdint>
#include <functional>
#include <memory>
#include <sstream>
#include <string.h>
#include <string>

using BofAssertCallback = std::function<BOFERR(const std::string &_rFile_S, uint32_t _Line_U32, const std::string &_rMasg_S)>;

#include <bofstd_export.h> //Autogenerated by cmake

#define BOF onbings::bof
#define BEGIN_BOF_NAMESPACE()                                                                                                                                                                                                                                  \
  namespace onbings                                                                                                                                                                                                                                            \
  {                                                                                                                                                                                                                                                            \
  namespace bof                                                                                                                                                                                                                                                \
  {
#define END_BOF_NAMESPACE()                                                                                                                                                                                                                                    \
  }                                                                                                                                                                                                                                                            \
  }
#define USE_BOF_NAMESPACE() using namespace BOF;

BEGIN_BOF_NAMESPACE()

struct BOFSTD_EXPORT BOFSTDPARAM
{
  bool AssertInRelease_B;
  BofAssertCallback AssertCallback;

  BOFSTDPARAM()
  {
    Reset();
  }

  void Reset()
  {
    AssertInRelease_B = false;
    AssertCallback = nullptr;
  }
};

/*!
 * Summary
 * Definition of a color in the RGBA color space
 */
struct BOFSTD_EXPORT BOF_RGBA
{
  uint8_t r_U8; /*! Color R component(Red)*/
  uint8_t g_U8; /*! Color G component(Greeen)*/
  uint8_t b_U8; /*! Color B component(Blue)*/
  uint8_t a_U8; /*! Color alpha component(Opacity)*/
  BOF_RGBA()
  {
    Reset();
  }

  BOF_RGBA(uint8_t _r_U8, uint8_t _g_U8, uint8_t _b_U8, uint8_t _a_U8)
  {
    r_U8 = _r_U8;
    g_U8 = _g_U8;
    b_U8 = _b_U8;
    a_U8 = _a_U8;
  }

  void Reset()
  {
    r_U8 = 0;
    g_U8 = 0;
    b_U8 = 0;
    a_U8 = 0;
  }
};
/*!
 * Summary
 * Definition of a size entity
 */
struct BOFSTD_EXPORT BOF_SIZE
{
  uint32_t Width_U32;  /*! Width value*/
  uint32_t Height_U32; /*! Height value*/
  BOF_SIZE()
  {
    Reset();
  }

  BOF_SIZE(uint32_t _Width_U32, uint32_t _Height_U32)
  {
    Width_U32 = _Width_U32;
    Height_U32 = _Height_U32;
  }

  void Reset()
  {
    Width_U32 = 0;
    Height_U32 = 0;
  }
};

#define BOF_HANDLE uintptr_t
// typedef void *BOF_HANDLE;
// #define BOF_INVALID_HANDLE_VALUE    ((BOF_HANDLE)-1)
const uintptr_t BOF_INVALID_HANDLE_VALUE = ((uintptr_t)-1);
#define BOF_IS_HANDLE_VALID(handle) (((uintptr_t)(handle) != 0) && ((uintptr_t)(handle) != BOF::BOF_INVALID_HANDLE_VALUE))
#if defined(__cplusplus)
#define BOF_EXTERN_C extern "C"
#else
#define BOF_EXTERN_C
#endif

#define BOF_GET_FILE_FROM__FILE__(ptr)                                                                                                                                                                                                                         \
  {                                                                                                                                                                                                                                                            \
    ptr = strrchr(__FILE__, '/');                                                                                                                                                                                                                              \
    if (!ptr)                                                                                                                                                                                                                                                  \
      ptr = strrchr(__FILE__, '\\');                                                                                                                                                                                                                           \
    ptr = ptr ? ++ptr : __FILE__;                                                                                                                                                                                                                              \
  }
#define BOF_COMPUTE_DELTA(start, end, delta)                                                                                                                                                                                                                   \
  {                                                                                                                                                                                                                                                            \
    delta = (end > start) ? (end - start) : (start - end);                                                                                                                                                                                                     \
  }
#define BOF_SAFE_FREE(p)                                                                                                                                                                                                                                       \
  {                                                                                                                                                                                                                                                            \
    if ((p))                                                                                                                                                                                                                                                   \
    {                                                                                                                                                                                                                                                          \
      free((void *)p);                                                                                                                                                                                                                                         \
    }                                                                                                                                                                                                                                                          \
    (p) = nullptr;                                                                                                                                                                                                                                             \
  } /*! free a buffer */
#define BOF_SAFE_DELETE(p)                                                                                                                                                                                                                                     \
  {                                                                                                                                                                                                                                                            \
    if ((p))                                                                                                                                                                                                                                                   \
    {                                                                                                                                                                                                                                                          \
      delete (p);                                                                                                                                                                                                                                              \
    }                                                                                                                                                                                                                                                          \
    (p) = nullptr;                                                                                                                                                                                                                                             \
  } /*! Delete an object*/
#define BOF_SAFE_DELETE_ARRAY(p)                                                                                                                                                                                                                               \
  {                                                                                                                                                                                                                                                            \
    if ((p))                                                                                                                                                                                                                                                   \
    {                                                                                                                                                                                                                                                          \
      delete[] (p);                                                                                                                                                                                                                                            \
    }                                                                                                                                                                                                                                                          \
    (p) = nullptr;                                                                                                                                                                                                                                             \
  } /*! Delete an array of objects*/
#define BOF_NB_ELEM_IN_ARRAY(x) (sizeof((x)) / sizeof((x)[0]))
#define BOF_STRUCT_FIELD_OFFSET(Type, Field) (uintptr_t)(&(((Type *)0)->Field)) /*! Get structure field offset in byte*/
#define BOF_STRUCT_FIELD_SIZE(Type, Field) (sizeof(((Type *)0)->Field))         /*! Get structure field size in byte*/
#define BOF_SETORRESET_BIT_IN_BYTESTREAM(SetOrReset, BitNum, pByteStream)                                                                                                                                                                                      \
  {                                                                                                                                                                                                                                                            \
    if (SetOrReset)                                                                                                                                                                                                                                            \
    {                                                                                                                                                                                                                                                          \
      pByteStream[BitNum >> 3] |= (1 << (BitNum & 0x07));                                                                                                                                                                                                      \
    }                                                                                                                                                                                                                                                          \
    else                                                                                                                                                                                                                                                       \
    {                                                                                                                                                                                                                                                          \
      pByteStream[BitNum >> 3] &= (0xFF - (1 << (BitNum & 0x07)));                                                                                                                                                                                             \
    }                                                                                                                                                                                                                                                          \
  }
#define BOF_ISBIT_IN_BYTESTREAM_SET(Sts, BitNum, pByteStream)                                                                                                                                                                                                  \
  {                                                                                                                                                                                                                                                            \
    Sts = (pByteStream[BitNum >> 3] & (1 << (BitNum & 0x07))) ? 1 : 0;                                                                                                                                                                                         \
  }
// #define BOF_ALIGN_PADDING_MAX(v, a)                                                   ((((v) % (a)) != 0) ? ((a)-((v) % (a))) : a)  //If aligned add a zone of a byte before the next one
#define BOF_ALIGN_ADD_NB_PADDING_BYTE(v, a) ((((v) % (a)) != 0) ? ((a) - ((v) % (a))) : 0) // If aligned add a zone of a byte before the next one
#define BOF_ALIGN_VALUE_ON(v, a) (((v) + (a)-1) & ~((a)-1))
#define BOF_SNPRINTF_NULL_CLIPPED(pBuffer, MaxBufferSize, Format, ...)                                                                                                                                                                                         \
  {                                                                                                                                                                                                                                                            \
    snprintf(pBuffer, MaxBufferSize, Format, ##__VA_ARGS__);                                                                                                                                                                                                   \
    pBuffer[MaxBufferSize - 1] = 0;                                                                                                                                                                                                                            \
  }
// Use Bof_StrNCpy #define BOF_STRNCPY_NULL_CLIPPED(pDst, pSrc, Count)                                     {strncpy(pDst, pSrc, Count);pDst[Count-1]=0;}
#define BOF_SET_ADDRESS_MAGIC_NUMBER(p, mn)                                                                                                                                                                                                                    \
  {                                                                                                                                                                                                                                                            \
    (p)->MagicNumber_U64 = (reinterpret_cast<uint64_t>(p) ^ static_cast<uint64_t>(mn));                                                                                                                                                                        \
  }
#define BOF_CHECK_ADDRESS_MAGIC_NUMBER(s, p, mn)                                                                                                                                                                                                               \
  {                                                                                                                                                                                                                                                            \
    if (p)                                                                                                                                                                                                                                                     \
    {                                                                                                                                                                                                                                                          \
      s = ((reinterpret_cast<uint64_t>(p) ^ (p)->MagicNumber_U64) == static_cast<uint64_t>(mn));                                                                                                                                                               \
    }                                                                                                                                                                                                                                                          \
    else                                                                                                                                                                                                                                                       \
      s = 0;                                                                                                                                                                                                                                                   \
  }
/*https://stackoverflow.com/questions/15832301/understanding-container-of-macro-in-the-linux-kernel
Taking this container for example:
struct container {
  int some_other_data;
  int this_data;
}
And a pointer int *my_ptr to the this_data member you'd use the macro to get a pointer to struct container *my_container by using:
struct container *my_container;	my_container = container_of(my_ptr, struct container, this_data);
*/
#define BOF_CONTAINER_OF(ptr, type, member)                                                                                                                                                                                                                    \
  ({                                                                                                                                                                                                                                                           \
    const typeof(((type *)0)->member) *__mptr = (ptr);                                                                                                                                                                                                         \
    (type *)((char *)__mptr - offsetof(type, member));                                                                                                                                                                                                         \
  })

// https://riptutorial.com/cplusplus/example/15335/casting-std--shared-ptr-pointers*/
// Note that std::reinterpret_pointer_cast is not available in C++11 and C++14, as it was only proposed by N3920 and adopted into Library Fundamentals TS in February 2014.
// However, it can be implemented as follows:
template <typename To, typename From> inline std::shared_ptr<To> reinterpret_pointer_cast(std::shared_ptr<From> const &ptr) noexcept
{
  return std::shared_ptr<To>(ptr, reinterpret_cast<To *>(ptr.get()));
}

#define BOF_EXTERN_C extern "C"
#define BOF_EXTERN_C_BEGIN                                                                                                                                                                                                                                     \
  extern "C"                                                                                                                                                                                                                                                   \
  {
#define BOF_EXTERN_C_END                                                                                                                                                                                                                                       \
  }                                                                                                                                                                                                                                                            \
  ;
extern uint32_t GL_BofDbgPrintfStartTime_U32;
#define BOF_DBG_PRINTF(Format, ...)                                                                                                                                                                                                                            \
  {                                                                                                                                                                                                                                                            \
    printf("%10d [%08X] " Format, BOF::Bof_GetMsTickCount() - BOF::GL_BofDbgPrintfStartTime_U32, BOF::Bof_CurrentThreadId(), ##__VA_ARGS__);                                                                                                                   \
  }

#if !defined(NDEBUG)
// #define BOF_ASSERT(_Expression)																													assert( (_Expression) )
// This one is better to use with gtest to avoid gtest aborf
// #define BOF_ASSERT(_Expression)                                                         (void)( ( (_Expression) ) || (GL_BofStdParam_X.AssertCallback ? GL_BofStdParam_X.AssertCallback(__FILE__,__LINE__,#_Expression):printf("Assertion failed: %s, file
// %s, line %d\nPress any key followed by enter to abort the application...",#_Expression, __FILE__, __LINE__), getchar(), abort(), 0) )
#define BOF_ASSERT(_Expression)                                                                                                                                                                                                                                \
  (void)(((_Expression)) || (GL_BofStdParam_X.AssertCallback ? static_cast<int>(GL_BofStdParam_X.AssertCallback(__FILE__, __LINE__, #_Expression))                                                                                                             \
                                                             : printf("Assertion failed: %s, file %s, line %d\nPress any key followed by enter to abort the application...", #_Expression, __FILE__, __LINE__),                                                \
                             getchar(), abort(), 0))
#else
// #define BOF_ASSERT(_Expression)																													assert( (_Expression) )	//Void op by default in release
// Microsoft assert.h: #define assert(_Expression) (void)( (!!(_Expression)) || (_wassert(_CRT_WIDE(#_Expression), _CRT_WIDE(__FILE__), __LINE__), 0) )
// #define BOF_ASSERT(_Expression)                                                         if (GL_BofStdParam_X.AssertInRelease_B){(void)( ( (_Expression) ) || (GL_BofStdParam_X.AssertCallback ?
// GL_BofStdParam_X.AssertCallback(__FILE__,__LINE__,#_Expression):printf("Assertion failed: %s, file %s, line %d\nPress any key followed by enter to abort the application...",#_Expression, __FILE__, __LINE__), getchar(), abort(), 0) );}
#define BOF_ASSERT(_Expression)                                                                                                                                                                                                                                \
  if (GL_BofStdParam_X.AssertInRelease_B)                                                                                                                                                                                                                      \
  {                                                                                                                                                                                                                                                            \
    (void)(((_Expression)) || (GL_BofStdParam_X.AssertCallback ? static_cast<int>(GL_BofStdParam_X.AssertCallback(__FILE__, __LINE__, #_Expression))                                                                                                           \
                                                               : printf("Assertion failed: %s, file %s, line %d\nPress any key followed by enter to abort the application...", #_Expression, __FILE__, __LINE__),                                              \
                               getchar(), abort(), 0));                                                                                                                                                                                                        \
  }
// #define BOF_ASSERT(_Expression)
#endif

/*
 * 3 steps:
 * 1. Check if bit in first byte of current byte stream position
 * 2. If not found find first byte containing bits
 * 3. Scan byte to find bits
 */
#define BOF_LOOKFORBIT_BIT_IN_BYTESTREAM(SetOrReset, BitNum, MaxBitNum, pByteStream)                                                                                                                                                                           \
  {                                                                                                                                                                                                                                                            \
    unsigned int i;                                                                                                                                                                                                                                            \
    bool StsBit;                                                                                                                                                                                                                                               \
    U32 FoundBitNum = (U32)-1;                                                                                                                                                                                                                                 \
    uint8_t MaskOfFirstByte, Val;                                                                                                                                                                                                                              \
    MaskOfFirstByte = 0xFF ^ ((1 << (BitNum & 0x07)) - 1);                                                                                                                                                                                                     \
    if (SetOrReset)                                                                                                                                                                                                                                            \
    {                                                                                                                                                                                                                                                          \
      StsBit = (pByteStream[(BitNum >> 3)] & MaskOfFirstByte);                                                                                                                                                                                                 \
    }                                                                                                                                                                                                                                                          \
    else                                                                                                                                                                                                                                                       \
    {                                                                                                                                                                                                                                                          \
      StsBit = (pByteStream[(BitNum >> 3)] & MaskOfFirstByte) != MaskOfFirstByte;                                                                                                                                                                              \
    }                                                                                                                                                                                                                                                          \
    if (!StsBit)                                                                                                                                                                                                                                               \
    {                                                                                                                                                                                                                                                          \
      Val = SetOrReset ? 0x00 : 0xFF;                                                                                                                                                                                                                          \
      for (i = (BitNum >> 3) + 1; i < (MaxBitNum >> 3); i++)                                                                                                                                                                                                   \
      {                                                                                                                                                                                                                                                        \
        if (pByteStream[i] != Val)                                                                                                                                                                                                                             \
        {                                                                                                                                                                                                                                                      \
          StsBit = true;                                                                                                                                                                                                                                       \
          break;                                                                                                                                                                                                                                               \
        }                                                                                                                                                                                                                                                      \
      }                                                                                                                                                                                                                                                        \
      BitNum = i << 3;                                                                                                                                                                                                                                         \
    }                                                                                                                                                                                                                                                          \
    if (StsBit)                                                                                                                                                                                                                                                \
    {                                                                                                                                                                                                                                                          \
      for (i = BitNum; i < BitNum + 8; i++)                                                                                                                                                                                                                    \
      {                                                                                                                                                                                                                                                        \
        BOF_ISBIT_IN_BYTESTREAM_SET(StsBit, i, pByteStream);                                                                                                                                                                                                   \
        if (StsBit == SetOrReset)                                                                                                                                                                                                                              \
        {                                                                                                                                                                                                                                                      \
          FoundBitNum = i;                                                                                                                                                                                                                                     \
          break;                                                                                                                                                                                                                                               \
        }                                                                                                                                                                                                                                                      \
      }                                                                                                                                                                                                                                                        \
    }                                                                                                                                                                                                                                                          \
    BitNum = FoundBitNum;                                                                                                                                                                                                                                      \
  }

#define BOF_SWAP16(ValToSwap)                                                                                                                                                                                                                                  \
  {                                                                                                                                                                                                                                                            \
    ((uint8_t *)&(ValToSwap))[0] ^= ((uint8_t *)&(ValToSwap))[1];                                                                                                                                                                                              \
    ((uint8_t *)&(ValToSwap))[1] ^= ((uint8_t *)&(ValToSwap))[0];                                                                                                                                                                                              \
    ((uint8_t *)&(ValToSwap))[0] ^= ((uint8_t *)&(ValToSwap))[1];                                                                                                                                                                                              \
  }

#define BOF_SWAP16PTR(pValToSwap)                                                                                                                                                                                                                              \
  {                                                                                                                                                                                                                                                            \
    ((uint8_t *)(pValToSwap))[0] ^= ((uint8_t *)(pValToSwap))[1];                                                                                                                                                                                              \
    ((uint8_t *)(pValToSwap))[1] ^= ((uint8_t *)(pValToSwap))[0];                                                                                                                                                                                              \
    ((uint8_t *)(pValToSwap))[0] ^= ((uint8_t *)(pValToSwap))[1];                                                                                                                                                                                              \
  }

#define BOF_SWAP32(ValToSwap)                                                                                                                                                                                                                                  \
  {                                                                                                                                                                                                                                                            \
    ((uint8_t *)&(ValToSwap))[0] ^= ((uint8_t *)&(ValToSwap))[3];                                                                                                                                                                                              \
    ((uint8_t *)&(ValToSwap))[3] ^= ((uint8_t *)&(ValToSwap))[0];                                                                                                                                                                                              \
    ((uint8_t *)&(ValToSwap))[0] ^= ((uint8_t *)&(ValToSwap))[3];                                                                                                                                                                                              \
    ((uint8_t *)&(ValToSwap))[1] ^= ((uint8_t *)&(ValToSwap))[2];                                                                                                                                                                                              \
    ((uint8_t *)&(ValToSwap))[2] ^= ((uint8_t *)&(ValToSwap))[1];                                                                                                                                                                                              \
    ((uint8_t *)&(ValToSwap))[1] ^= ((uint8_t *)&(ValToSwap))[2];                                                                                                                                                                                              \
  }

#define BOF_SWAP32PTR(pValToSwap)                                                                                                                                                                                                                              \
  {                                                                                                                                                                                                                                                            \
    ((uint8_t *)(pValToSwap))[0] ^= ((uint8_t *)(pValToSwap))[3];                                                                                                                                                                                              \
    ((uint8_t *)(pValToSwap))[3] ^= ((uint8_t *)(pValToSwap))[0];                                                                                                                                                                                              \
    ((uint8_t *)(pValToSwap))[0] ^= ((uint8_t *)(pValToSwap))[3];                                                                                                                                                                                              \
    ((uint8_t *)(pValToSwap))[1] ^= ((uint8_t *)(pValToSwap))[2];                                                                                                                                                                                              \
    ((uint8_t *)(pValToSwap))[2] ^= ((uint8_t *)(pValToSwap))[1];                                                                                                                                                                                              \
    ((uint8_t *)(pValToSwap))[1] ^= ((uint8_t *)(pValToSwap))[2];                                                                                                                                                                                              \
  }

#define BOF_SWAP64(ValToSwap)                                                                                                                                                                                                                                  \
  {                                                                                                                                                                                                                                                            \
    ((uint8_t *)&(ValToSwap))[0] ^= ((uint8_t *)&(ValToSwap))[7];                                                                                                                                                                                              \
    ((uint8_t *)&(ValToSwap))[7] ^= ((uint8_t *)&(ValToSwap))[0];                                                                                                                                                                                              \
    ((uint8_t *)&(ValToSwap))[0] ^= ((uint8_t *)&(ValToSwap))[7];                                                                                                                                                                                              \
    ((uint8_t *)&(ValToSwap))[1] ^= ((uint8_t *)&(ValToSwap))[6];                                                                                                                                                                                              \
    ((uint8_t *)&(ValToSwap))[6] ^= ((uint8_t *)&(ValToSwap))[1];                                                                                                                                                                                              \
    ((uint8_t *)&(ValToSwap))[1] ^= ((uint8_t *)&(ValToSwap))[6];                                                                                                                                                                                              \
    ((uint8_t *)&(ValToSwap))[2] ^= ((uint8_t *)&(ValToSwap))[5];                                                                                                                                                                                              \
    ((uint8_t *)&(ValToSwap))[5] ^= ((uint8_t *)&(ValToSwap))[2];                                                                                                                                                                                              \
    ((uint8_t *)&(ValToSwap))[2] ^= ((uint8_t *)&(ValToSwap))[5];                                                                                                                                                                                              \
    ((uint8_t *)&(ValToSwap))[3] ^= ((uint8_t *)&(ValToSwap))[4];                                                                                                                                                                                              \
    ((uint8_t *)&(ValToSwap))[4] ^= ((uint8_t *)&(ValToSwap))[3];                                                                                                                                                                                              \
    ((uint8_t *)&(ValToSwap))[3] ^= ((uint8_t *)&(ValToSwap))[4];                                                                                                                                                                                              \
  }

#define BOF_SWAP64PTR(pValToSwap)                                                                                                                                                                                                                              \
  {                                                                                                                                                                                                                                                            \
    ((uint8_t *)(pValToSwap))[0] ^= ((uint8_t *)(pValToSwap))[7];                                                                                                                                                                                              \
    ((uint8_t *)(pValToSwap))[7] ^= ((uint8_t *)(pValToSwap))[0];                                                                                                                                                                                              \
    ((uint8_t *)(pValToSwap))[0] ^= ((uint8_t *)(pValToSwap))[7];                                                                                                                                                                                              \
    ((uint8_t *)(pValToSwap))[1] ^= ((uint8_t *)(pValToSwap))[6];                                                                                                                                                                                              \
    ((uint8_t *)(pValToSwap))[6] ^= ((uint8_t *)(pValToSwap))[1];                                                                                                                                                                                              \
    ((uint8_t *)(pValToSwap))[1] ^= ((uint8_t *)(pValToSwap))[6];                                                                                                                                                                                              \
    ((uint8_t *)(pValToSwap))[2] ^= ((uint8_t *)(pValToSwap))[5];                                                                                                                                                                                              \
    ((uint8_t *)(pValToSwap))[5] ^= ((uint8_t *)(pValToSwap))[2];                                                                                                                                                                                              \
    ((uint8_t *)(pValToSwap))[2] ^= ((uint8_t *)(pValToSwap))[5];                                                                                                                                                                                              \
    ((uint8_t *)(pValToSwap))[3] ^= ((uint8_t *)(pValToSwap))[4];                                                                                                                                                                                              \
    ((uint8_t *)(pValToSwap))[4] ^= ((uint8_t *)(pValToSwap))[3];                                                                                                                                                                                              \
    ((uint8_t *)(pValToSwap))[3] ^= ((uint8_t *)(pValToSwap))[4];                                                                                                                                                                                              \
  }

#define BOF_BIND_0_ARG_TO_METHOD(pThis, Class_ColonColon_Method) std::bind(&Class_ColonColon_Method, pThis)
#define BOF_BIND_1_ARG_TO_METHOD(pThis, Class_ColonColon_Method) std::bind(&Class_ColonColon_Method, pThis, std::placeholders::_1)
#define BOF_BIND_2_ARG_TO_METHOD(pThis, Class_ColonColon_Method) std::bind(&Class_ColonColon_Method, pThis, std::placeholders::_1, std::placeholders::_2)
#define BOF_BIND_3_ARG_TO_METHOD(pThis, Class_ColonColon_Method) std::bind(&Class_ColonColon_Method, pThis, std::placeholders::_1, std::placeholders::_2, std::placeholders::_3)
#define BOF_BIND_4_ARG_TO_METHOD(pThis, Class_ColonColon_Method) std::bind(&Class_ColonColon_Method, pThis, std::placeholders::_1, std::placeholders::_2, std::placeholders::_3, std::placeholders::_4)
#define BOF_BIND_5_ARG_TO_METHOD(pThis, Class_ColonColon_Method) std::bind(&Class_ColonColon_Method, pThis, std::placeholders::_1, std::placeholders::_2, std::placeholders::_3, std::placeholders::_4, std::placeholders::_5)
#define BOF_BIND_6_ARG_TO_METHOD(pThis, Class_ColonColon_Method) std::bind(&Class_ColonColon_Method, pThis, std::placeholders::_1, std::placeholders::_2, std::placeholders::_3, std::placeholders::_4, std::placeholders::_5, std::placeholders::_6)
#define BOF_BIND_7_ARG_TO_METHOD(pThis, Class_ColonColon_Method)                                                                                                                                                                                               \
  std::bind(&Class_ColonColon_Method, pThis, std::placeholders::_1, std::placeholders::_2, std::placeholders::_3, std::placeholders::_4, std::placeholders::_5, std::placeholders::_6, std::placeholders::_7)
#define BOF_BIND_8_ARG_TO_METHOD(pThis, Class_ColonColon_Method)                                                                                                                                                                                               \
  std::bind(&Class_ColonColon_Method, pThis, std::placeholders::_1, std::placeholders::_2, std::placeholders::_3, std::placeholders::_4, std::placeholders::_5, std::placeholders::_6, std::placeholders::_7, std::placeholders::_8)

BOFSTD_EXPORT BOFERR Bof_Initialize(const BOFSTDPARAM &_rStdParam_X);

BOFSTD_EXPORT BOFERR Bof_Shutdown();

BOFSTD_EXPORT std::string Bof_GetVersion();

BOFSTD_EXPORT const char *Bof_ErrorCode(BOFERR _ErrorCode_E);

BOFSTD_EXPORT bool Bof_IsWindows();

template <typename T> BOFERR Bof_StringToBin(uint32_t _Base_U32, const char *_pAsciiNumber_c, T &_rConvertedValue)
{
  BOFERR Rts_E = BOF_ERR_EINVAL;
  char *p_c;
  int64_t Nb_S64;

  _rConvertedValue = 0;
  if ((_pAsciiNumber_c) && ((_Base_U32 == 0) || ((_Base_U32 >= 2) && (_Base_U32 <= 36))))
  {
    Nb_S64 = strtol(_pAsciiNumber_c, &p_c, _Base_U32);
    if (*p_c == 0) // else not a number
    {
      Rts_E = BOF_ERR_NO_ERROR;
      _rConvertedValue = static_cast<T>(Nb_S64);
    }
    else
    {
      Rts_E = BOF_ERR_ENOKEY;
    }
  }
  return Rts_E;
}

template <typename T> inline T BOF_MIN(T _Val1, T _Val2)
{
  return (_Val1 < _Val2) ? _Val1 : _Val2;
}

template <typename T> inline T BOF_MAX(T _Val1, T _Val2)
{
  return (_Val1 > _Val2) ? _Val1 : _Val2;
}

class BOFSTD_EXPORT BofException : public std::exception
{
public:
  BofException(std::string _Header_S, std::string _Context_S = "", std::string _Where_S = "", int32_t _ErrorCode_S32 = 0);
  char const *what() const noexcept override; // throw ();

private:
  std::string mHeader_S;
  BOFERR mErrorCode_E;
  std::string mContext_S;
  std::string mWhere_S;

  std::string mMessage_S;
};
#define THROW_BOF_EXCEPTION(Header, Context, ErrorCode)                                                                                                                                                                                                        \
  {                                                                                                                                                                                                                                                            \
    std::ostringstream Where;                                                                                                                                                                                                                                  \
    Where << __FILE__ << ':' << __LINE__ << " (" << __func__ << ')';                                                                                                                                                                                           \
    BOF::BofException Exception(Header, Context, Where.str(), ErrorCode);                                                                                                                                                                                      \
    throw Exception;                                                                                                                                                                                                                                           \
  }

END_BOF_NAMESPACE()

extern BOFSTD_EXPORT BOF::BOFSTDPARAM GL_BofStdParam_X;
